version: '3.8'

services:
  jenkins:
    build:
      context: .             # Build from Dockerfile in current folder
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Required for Jenkins to access Docker
    restart: unless-stopped

volumes:
  jenkins_home:
